name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
    - name: Build release
      run: cargo build --release --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows_release
        path: target/release/wordgames-client.exe
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
    - name: Build release
      run: cargo build --release --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos_release
        path: target/release/wordgames-client
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: rui314/setup-mold@v1
    - uses: actions/checkout@v4
    - name: Soft link mold linker
      run: ln -s /usr/local/bin/mold /usr/bin/mold
    - name: Run tests
      run: cargo test --verbose
    - name: Build release
      run: cargo build --release --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux_release
        path: target/release/wordgames-client
